version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO_BASE_URL
  build:
    commands:
      - echo Build started on `date`
      - echo Building docker image...
      - docker build -t $ECR_IMAGE_NAME .
      - docker tag $ECR_IMAGE_NAME:latest $ECR_REPO_BASE_URL/$ECR_IMAGE_NAME:latest
  post_build:
    commands: 
      - echo Build completed on `date`
      - echo Pushing the docker image
      - docker push $ECR_REPO_BASE_URL/$ECR_IMAGE_NAME:latest
      - echo Writing image definitions file...
      - echo '[{"name":"'$ECR_IMAGE_NAME'","imageUri":"'$ECR_REPO_BASE_URL'/'$ECR_IMAGE_NAME':latest"}]' > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json