version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm ci
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands: 
      - cp -R node_modules/ dist/node_modules # nodejs needs this
      - cp Procfile dist/Procfile # EBS needs this
      - cp package.json dist/package.json # EBS needs this
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist