version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 217970293372.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building docker image...
      - docker build -t chat-api .
      - docker tag chat-api:latest 217970293372.dkr.ecr.us-east-1.amazonaws.com/chat-api:latest
  post_build:
    commands: 
      - echo Build completed on `date`
      - echo Pushing the docker image
      - docker push 217970293372.dkr.ecr.us-east-1.amazonaws.com/chat-api:latest