version: '3'
services:
  api:
    build: .
    extends:
      file: docker-compose.${ENV}.yaml
      service: api
    depends_on:
      - database
    links:
      - database
  database:
    image: postgres:14.7-alpine
    ports:
      - ${DATABASE_PORT}:5432
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
